spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/black_friday?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: 127.0.0.1:19092,127.0.0.1:19093,127.0.0.1:19094
    consumer:
      group-id: delivery-request-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

---

spring:
  config:
    activate:
      on-profile: staging
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/black_friday?useSSL=false&allowPublicKeyRetrieval=true # Docker 로 띄운 MySQL 서비스 이름: mysql
    username: root
    password: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
    consumer:
      group-id: delivery-request-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false